### ISSUE TITLE
doesn't work on windows

### ISSUE THREAD

**Issue by MorphicResonance** [bitspook/spookfox#25]
unfortunately, it doesn't work on windows. Firefox freezes when plugin is active. And emacs loads with error something as 'no such file or directory websocket' . Turned it off.

**Comment by bitspook** [comment]
Thanks for reporting this @MorphicResonance 

There is indeed a bug in the firefox extension which make Firefox freeze. I've reported it as #26 
This has an easy work-around for now, which is restarting Firefox once Emacs is up and running (with spookfox's websockets server up and running).

If you installed the Emacs package for spookfox manually (i.e without straight.el), you might need to setup websocket Emacs package. You can do `(use-package websocket)` before trying to load spookfox.

In the meanwhile, I'll try to set a windows VM to try it out on windows. But it might take some time before I get around to do that because I am running a little busy with life stuff these days.

Thanks again.

**Comment by MorphicResonance** [comment]
It freeze hard if you start firefox *before* emacs but if you start firefox after emacs it works on windows.
Broadly speaking it works with firefox on windows.

**Comment by bitspook** [comment]
Thanks for the update @MorphicResonance . I suppose in that case we can close this issue in favor of #26 Please feel free to re-open if I misunderstood you.
