### ISSUE TITLE
Unable to register apps properly, or incorrect documentation

### ISSUE THREAD

**Issue by seanhagen** [bitspook/spookfox#34]
It seems like I'm unable to register the Spookfox apps properly for some reason.

I set up Spookfox in Emacs like so:

```elisp
(use-package spookfox
  :straight (spookfox :type git :host github :repo "bitspook/spookfox" :files ("lisp/*.el" "lisp/apps/*.el"))
  :config
  (require 'spookfox-tabs)
  (require 'spookfox-js-injection)
  (require 'spookfox-org-tabs)

  (add-to-list 'spookfox-enabled-apps 'spookfox-tabs)
  (add-to-list 'spookfox-enabled-apps 'spookfox-org-tabs)
  (add-to-list 'spookfox-enabled-apps 'spookfox-js-injection)
  (setq spookfox-debug t)
  (spookfox-init))
```

And installed the extension in Firefox.

I opened the debug console for Spookfox, and it looks like only the JSCL app gets loaded in the extension. At least, I think that's what's going on from the logs:

![image](https://github.com/bitspook/spookfox/assets/444767/d9e7a08a-4c2a-4ee9-a3cd-157a84465df4)

When I take a look at the `*spookfox*` buffer in Emacs, I see this:

```
[DISCONNECTED] Total clients: 0
[CONNECTED] Total clients: 1
[MESSAGE] {"requestId":"0dcb66dd-e219-4d08-a8c2-7d1ef4d44ef0","payload":{"status":"error","message":"Uknown app null"}}
```

If I try to eval the following Org `src` block ( using some elisp from [Sacha Chua](https://sachachua.com/blog/2024/01/running-the-current-org-mode-babel-javascript-block-in-spookfox/) ):

```org
#+begin_src js :eval never-export :spookfox t :exports results
[...document.querySelectorAll('.post > h2')].slice(0,5).map((o) => '- ' + o.textContent.trim().replace(/[ \n]+/g, ' ') + '\n').join('')
#+end_src
```

The Spookfox debug console shows the following:
![image](https://github.com/bitspook/spookfox/assets/444767/67d85cb9-780c-49d7-a699-ea35b8c627bc)

## Update after some testing

It looks like my Emacs configuration was wrong. After looking at [your (bitspook) Emacs config](https://github.com/bitspook/spookmax.d/?tab=readme-ov-file#applications), I updated my Emacs config to be the following:

```elisp
(use-package spookfox
  :straight (spookfox :type git :host github :repo "bitspook/spookfox" :files ("lisp/*.el" "lisp/apps/*.el"))
  :config
  (setq spookfox-enabled-apps (list spookfox-org-tabs spookfox-tabs spookfox-js-injection))
  (setq spookfox-debug t)
  (spookfox-init))
```

That seems to have fixed things.

The `(require ...)` lines I put in because that's how the project page says to do things:
![image](https://github.com/bitspook/spookfox/assets/444767/8c1e4196-743c-4866-97f2-f61f0e6f930f)

Seeing as removing the `require` statements was got `spookfox` working for me, does the documentation need to be updated?

In any case, it seems like things are mostly working -- although org-tabs doesn't sem to be working:
![image](https://github.com/bitspook/spookfox/assets/444767/1c32c924-c84d-4d6a-953c-00b306c3f671)

**Comment by bitspook** [comment]
Hello @seanhagen,

Thanks for reporting the issue! And for making it so thorough ❤️ 

> does the documentation need to be updated?

Evidently so. But looks like there is something broken which makes documentation wrong, which should be fixed first. So I'll try to fix that instead.

> although org-tabs doesn't sem to be working

I am not surprised 😅 org-tabs was the reason I created spookfox in the first place, but then found it be useful for other things (mostly capturing information from Firefox and making ff do things from Emacs). Managing tabs outside ff is extremely tricky; spookfox could be much simpler if not for all the state-management org-tabs needs.

I have a [todo item to pivot org-tabs](https://github.com/bitspook/spookfox/issues/30) to do "Archive and unarchive open tabs" instead of "Keep a live org file which always stay in sync with ff tabs".

I will keep this issue open until I can replicate and fix the original problem you reported. 

Thanks again! And also thank you for linking Sacha Chua's post. I didn't know about it. It seems like a great idea and something that can/should be shipped with Spookfox itself.

**Comment by bitspook** [comment]
I tried to recreate the problem by adding `(require 'spookfox-js-injection)` to `use-package`, but was not able to. I tested a bunch of scenarios, but seems like although `require` isn't necessary, adding it doesn't hurt either. 

I am closing this issue. Please feel free to reopen.

(PS I think we need to re-think the "apps" concept; either make apps fully self-contained, i.e they live only in elisp files, or not have them at all.)
